### ISSUE TITLE
Es repo publica o un proyecto escolar?

### ISSUE THREAD

**Issue by cbhat5** [GersonBenito/SpringBoot-MovieManagement-API-Rest-Full#1]

**Comment by GersonBenito** [comment]
Es repo publico

**Comment by cbhat5** [comment]
¿Hay alguna issue o feature en el que puedo trabajar?

**Comment by GersonBenito** [comment]
Claro que si, puede agregar la feature de busqueda multiparametros de peliculas y el filtrado de peliculas por categorias, por favor

**Comment by cbhat5** [comment]
Además, esta diff muestra que su controllers tienen la mayor parte de la lógica que en realidad debería haber estado en la service layer. Espero poder refactorizar.

https://github.com/GersonBenito/SpringBoot-MovieManagement-API-Rest-Full/commit/ce6f2d50e22a13fa81b69e516f0a84904902f097#diff-ca60b3be84927eec79b28025af318feeccbf0e90ac56b1abd85b9ef21d4920ba

**Comment by GersonBenito** [comment]
De acuerdo, puede apoyarme con la refactozarizacion de los controllers, por favor

**Comment by cbhat5** [comment]
> el filtrado de peliculas por categorias

@GersonBenito  ¿categorias? ¿Te refieres a géneros?

**Comment by GersonBenito** [comment]
Correcto, perdon por la confusion de palabras
