### ISSUE TITLE
SQL DDL 

### ISSUE THREAD

**Issue by cbhat5** [GersonBenito/SpringBoot-MovieManagement-API-Rest-Full#5]
Por favor proporcione DDL para las tablas

**Comment by cbhat5** [comment]
@GersonBenito ¿Puedes extraer los DDLs de su DB?

**Comment by GersonBenito** [comment]
Se crean de forma automático con la propiedad ddlAuto=create-drop, esto está en el archivo de propiedades de spring boot

**Comment by GersonBenito** [comment]
Al iniciar el proyecto crea las tablas y inserta los datos de prueba del archivo import.sql, puede encontrar estos archivos en la carpeta de resources

**Comment by cbhat5** [comment]
oh ok, gracias

**Comment by GersonBenito** [comment]
Con gusto, tener en cuenta que el valor create-drop, crea las tablas siempre y cuando exista la base de datos en MySQL, adicional create-drop, crea las tablas al ejecutar el proyecto y borra las tablas al detener el proyecto, puede cambiar el tipo de valor de la propiedad dependiendo de su uso

**Comment by cbhat5** [comment]
si lo se.  De alguna manera me perdí el "create-drop"

**Comment by cbhat5** [comment]
@GersonBenito ¿Cómo desactivo la autenticación o puedes dar la contraseña? No tengo mucha experiencia en Spring Security.

**Comment by GersonBenito** [comment]
Puedes registrar un nuevo usuario con roles de ADMIN, USER y INVITED
```
Endpoint registro de usuarios: http://localhost:8080/api/v1/auth/register
{
    "email": "test.test@gmail.com",
    "username": "Test Test",
    "password": "893452346",
    "roles": ["ADMIN", "USER", "INVITED"],
    "image": "https://res.cloudinary.com/dokr7v5et/image/upload/v1695446663/ublw2vxl7fqzglaoumkk.png"
}

endpoint login de usuarios: http://localhost:8080/api/v1/auth/login
{
    "username":"Test Test",
    "password":"893452346"
}

```

**Comment by cbhat5** [comment]
Sí, ya lo intenté y obtuve 403 FORBIDDEN

![image](https://github.com/GersonBenito/SpringBoot-MovieManagement-API-Rest-Full/assets/47479435/5077d9d2-732e-4b5c-aac6-0bfd31ec7cba)

**Comment by cbhat5** [comment]
Ok done, gracias

**Comment by GersonBenito** [comment]
Debe de ser en el endpoint [http://localhost:8080/api/v1/auth/register](http://localhost:8080/api/v1/auth/register) para el registro de usuarios.

Y para el login [http://localhost:8080/api/v1/auth/login](http://localhost:8080/api/v1/auth/login)

**Comment by cbhat5** [comment]
It was 200 OK for register but 403 in login, also gave in Authorization along with request body for login

![image](https://github.com/GersonBenito/SpringBoot-MovieManagement-API-Rest-Full/assets/47479435/4dc33708-8d3e-46d5-b03c-71728fa820d7)

**Comment by cbhat5** [comment]
ok, looks like service restarted, worked now, but still GET movie is an issue?
![image](https://github.com/GersonBenito/SpringBoot-MovieManagement-API-Rest-Full/assets/47479435/e780df89-85c3-4763-bd0c-24ff17d1bd94)

**Comment by cbhat5** [comment]
Ok, i was able to use JWT token in Authorization and use it, thanks

**Comment by GersonBenito** [comment]
para el login es de esta forma
![image](https://github.com/GersonBenito/SpringBoot-MovieManagement-API-Rest-Full/assets/63212268/eec35b24-4fa2-4fde-ba2f-fcc23ca7e014)

Y para acceder al endpoint de peliculas debe de ser rol ADMIN y debes de usar el token obtenido del login para enviarlo en el hader Authorization 
![image](https://github.com/GersonBenito/SpringBoot-MovieManagement-API-Rest-Full/assets/63212268/a2c70bb6-8c65-468c-a599-838172accacd)

**Comment by GersonBenito** [comment]
Request model save a new a movie
```
{
    "title": "Scream VI",
    "description": "Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter.",
    "posterImage": "https://res.cloudinary.com/dokr7v5et/image/upload/v1695446663/ublw2vxl7fqzglaoumkk.png",
    "backgroundImage": "https://res.cloudinary.com/dokr7v5et/image/upload/v1695446663/ublw2vxl7fqzglaoumkk.png",
    "popularity": 184.046,
    "rentalPrice": 1.50,
    "purchasePrice": 2.50,
    "availability": true,
    "stock": {
        "id": 2,
        "amount": 40
    },
    "genres": [
        {
            "id": 10,
            "name": "Crime"
        },
        {
            "id": 2,
            "name": "Science fiction"
        },
        {
            "id": 7,
            "name": "Adventure"
        }
    ]
}
```

**Comment by cbhat5** [comment]
¿Por qué el stock es una table separada y no un BIGINT directamente en el MOVIE table?

**Comment by GersonBenito** [comment]
Estaba pensando que para poderle darle mantenimiento por separado
