### ISSUE TITLE
Multiparam GET

### ISSUE THREAD

**Issue by cbhat5** [GersonBenito/SpringBoot-MovieManagement-API-Rest-Full#7]

**Comment by cbhat5** [comment]
para multiparam, ¿queremos que se aplique la condición AND o OR a todos los parámetros?

**Comment by GersonBenito** [comment]
Sería la condición OR, para poder buscar por title, availability, rental price, purchase price, stock, popularity.

Y filtro de categoría.

No sería exactamente con todos los parámetros, si no que con los que se pueda realizar una búsqueda.

**Comment by cbhat5** [comment]
Oh, ok, he hecho la parte de la AND condición por ahora. Y hemos agregado una entrada de usuario para query por ANY(`any=true` -> OR) o AND (`any=false` -> AND). Solo necesitamos reemplazar `build.and` con `build.or` para la condición OR.

**Comment by cbhat5** [comment]
¿Puedes review #8 y merge?

**Comment by GersonBenito** [comment]
Super, Que bien de esta forma queda más dinámico

**Comment by GersonBenito** [comment]
> ¿Puedes review #8 y merge?

Listo, al parecer ya se hizo el merge
